import streamlit as st
import plotly.graph_objects as go
import pandas as pd

from api_client import get_province_trend
from components.cards import (
    metric_card,
    section_header,
    divider,
    info_box,
    page_footer,
)

PROVINCES = [
    "Central", "Copperbelt", "Eastern", "Luapula", "Lusaka",
    "Muchinga", "North-Western", "Northern", "Southern", "Western"
]


def render():
    st.write("Province Trends page loaded")


    section_header(
        "Risk Trends by Province",
        "Historical teacher attrition risk predictions generated by the XGBoost model"
    )

    # Province selector
    selected_province = st.selectbox(
        "Select Province",
        PROVINCES,
        index=4  # Default to Lusaka
    )

    # Load trend data from API
    trend_data = get_province_trend(selected_province)

    if not trend_data:
        st.warning("No trend data available for this province.")
        return

    df = pd.DataFrame(trend_data)

    # KPI cards
    latest = df.iloc[-1]
    high_risk_years = (df["risk_label"] == "high_risk").sum()

    c1, c2, c3, c4 = st.columns(4)

    with c1:
        metric_card(
            "Latest Risk Score",
            f"{latest['risk_score']:.2f}",
            f"Year {latest['year']}",
            accent="high" if latest["risk_label"] == "high_risk" else "low"
        )

    with c2:
        metric_card(
            "Risk Status",
            "High Risk" if latest["risk_label"] == "high_risk" else "Stable",
            "Current classification",
            accent="high" if latest["risk_label"] == "high_risk" else "low"
        )

    with c3:
        metric_card(
            "High-Risk Years",
            high_risk_years,
            f"Out of {len(df)} years",
            accent="high"
        )

    with c4:
        metric_card(
            "Average Risk",
            f"{df['risk_score'].mean():.2f}",
            "Historical average",
            accent="medium"
        )

    divider()

    # Risk score trend chart
    st.markdown(
        '<div class="section-label">Risk Score Trend</div>',
        unsafe_allow_html=True
    )

    fig = go.Figure()

    fig.add_trace(go.Scatter(
        x=df["year"],
        y=df["risk_score"],
        mode="lines+markers",
        line=dict(color="#2D6A4F", width=3),
        marker=dict(
            size=8,
            color=[
                "#DC2626" if r == "high_risk" else "#40916C"
                for r in df["risk_label"]
            ]
        ),
        name="Risk Score",
        hovertemplate="<b>%{x}</b><br>Risk Score: %{y:.3f}<extra></extra>"
    ))

    # Add risk threshold line
    fig.add_hline(
        y=0.65,
        line_dash="dash",
        line_color="#DC2626",
        annotation_text="High-Risk Threshold (0.65)",
        annotation_position="top left"
    )

    fig.update_layout(
        height=420,
        xaxis_title="Year",
        yaxis_title="Risk Score",
        yaxis=dict(range=[0, 1]),
        paper_bgcolor="rgba(0,0,0,0)",
        plot_bgcolor="rgba(0,0,0,0)",
        margin=dict(t=20, b=20, l=0, r=20),
        showlegend=False
    )

    st.plotly_chart(
        fig,
        use_container_width=True,
        config={"displayModeBar": False}
    )

    divider()

    # Contributing indicators
    st.markdown(
        '<div class="section-label">Contributing Indicators Over Time</div>',
        unsafe_allow_html=True
    )

    fig2 = go.Figure()

    fig2.add_trace(go.Scatter(
        x=df["year"],
        y=df["ptr_primary_calc"],
        mode="lines+markers",
        name="PTR",
        line=dict(width=2)
    ))

    fig2.add_trace(go.Scatter(
        x=df["year"],
        y=df["teacher_growth_rate"],
        mode="lines+markers",
        name="Teacher Growth %",
        line=dict(width=2)
    ))

    fig2.add_trace(go.Scatter(
        x=df["year"],
        y=df["recruitment_gap"],
        mode="lines+markers",
        name="Recruitment Gap",
        line=dict(width=2)
    ))

    fig2.update_layout(
        height=420,
        xaxis_title="Year",
        yaxis_title="Indicator Value",
        paper_bgcolor="rgba(0,0,0,0)",
        plot_bgcolor="rgba(0,0,0,0)",
        margin=dict(t=20, b=20, l=0, r=20),
        legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1)
    )

    st.plotly_chart(
        fig2,
        width="stretch",
        config={"displayModeBar": False}
    )

    divider()

    # Trend table
    st.markdown(
        '<div class="section-label">Historical Risk Register</div>',
        unsafe_allow_html=True
    )

    display_df = df[[
        "year",
        "risk_score",
        "risk_label",
        "ptr_primary_calc",
        "teacher_growth_rate",
        "recruitment_gap",
        "attrition_proxy_rate"
    ]].copy()

    display_df.columns = [
        "Year",
        "Risk Score",
        "Risk Label",
        "PTR",
        "Teacher Growth %",
        "Recruitment Gap",
        "Attrition Proxy"
    ]

    st.dataframe(
        display_df,
        width="stretch",
        hide_index=True,
        height=350
    )

    divider()

    # Interpretation panel
    latest_year = latest["year"]
    latest_score = latest["risk_score"]
    latest_label = latest["risk_label"].replace("_", " ").title()

    info_box(
        f"""
        <strong>Interpretation for {selected_province}:</strong>
        In {latest_year}, {selected_province} recorded a risk score of <strong>{latest_score:.2f}</strong>,
        classified as <strong>{latest_label}</strong>.

        The trend chart helps identify whether the province has experienced persistent risk,
        sudden spikes, or periods of stability. This supports evidence-based teacher deployment
        and retention planning by highlighting when risk conditions worsened.
        """
    )

    page_footer()


